version: '3.8'
services:
  dev-db:
    image: postgres:17
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12341234
      POSTGRES_DB: fcc_vlad_bookmark
    networks:
      - freecodecamp
  test-db:
    image: postgres:17
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12341234
      POSTGRES_DB: fcc_vlad_bookmark
    networks:
      - freecodecamp
networks:
  freecodecamp:
